### ISSUE TITLE
How to install this package

### ISSUE THREAD

**Issue by sophyda** [jakeret/unet#7]
I want to install this in miniconda by inputing'python setup.py install' in Anaconda Prompt .But Error:  AttributeError: 'Configuration' object has no attribute 'parentdir_prefix_version'    Would you tell me why?Thanks!!!

**Comment by jakeret** [comment]
I just tried it with a fresh conda env and in ran through.

Could you describe the steps you did to install it. 
What OS are you using? What is the version of your miniconda?

**Comment by sophyda** [comment]
OS : Windows 10
In Miniconda Prompt:
(base) C:\Users\sophyda>conda -V
conda 4.8.4

(base) C:\Users\sophyda>G:

(base) G:\>cd G:\unet-master

(base) G:\unet-master>python setup.py install
Traceback (most recent call last):
  File "setup.py", line 23, in <module>
    setup(use_pyscaffold=True)
  File "A:\Miniconda\lib\site-packages\setuptools\__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "A:\Miniconda\lib\distutils\core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "A:\Miniconda\lib\site-packages\setuptools\dist.py", line 448, in __init__
    k: v for k, v in attrs.items()
  File "A:\Miniconda\lib\distutils\dist.py", line 292, in __init__
    self.finalize_options()
  File "A:\Miniconda\lib\site-packages\setuptools\dist.py", line 740, in finalize_options
    ep.load()(self)
  File "A:\Miniconda\lib\site-packages\setuptools\dist.py", line 747, in _finalize_setup_keywords
    ep.load()(self, ep.name, value)
  File "g:\unet-master\.eggs\pyscaffold-3.2.3-py3.7.egg\pyscaffold\integration.py", line 105, in pyscaffold_keyword
    version_keyword(dist, keyword, setuptools_scm_config(value))
  File "g:\unet-master\.eggs\pyscaffold-3.2.3-py3.7.egg\pyscaffold\contrib\setuptools_scm\integration.py", line 17, in version_keyword
    dist.metadata.version = get_version(**value)
  File "g:\unet-master\.eggs\pyscaffold-3.2.3-py3.7.egg\pyscaffold\contrib\setuptools_scm\__init__.py", line 150, in get_version
    parsed_version = _do_parse(config)
  File "g:\unet-master\.eggs\pyscaffold-3.2.3-py3.7.egg\pyscaffold\contrib\setuptools_scm\__init__.py", line 99, in _do_parse
    config, fallback=True
  File "g:\unet-master\.eggs\pyscaffold-3.2.3-py3.7.egg\pyscaffold\contrib\setuptools_scm\__init__.py", line 58, in _version_from_entrypoints
    version = _call_entrypoint_fn(root, config, ep.load())
  File "g:\unet-master\.eggs\pyscaffold-3.2.3-py3.7.egg\pyscaffold\contrib\setuptools_scm\__init__.py", line 39, in _call_entrypoint_fn
    return fn(root, config=config)
  File "A:\Miniconda\lib\site-packages\setuptools_scm\hacks.py", line 28, in fallback_version
    if config.parentdir_prefix_version is not None:
AttributeError: 'Configuration' object has no attribute 'parentdir_prefix_version'


I am a beginner in this field .Maybe it's a simple question .I would appreciate it if you could help me
